### ISSUE TITLE
Crosswords feed not exposed

### ISSUE THREAD

**Issue by thisisparker** [adamaaronson/adamaaronson.github.io#3]
Hi Adam,

Forgive me if this is not the right venue, but I was looking for an RSS feed for your new puzzles, and I saw that you had `jekyll-feed` set up, but the `alternate` link on your page points to the empty "posts" collection, not the (filled out) `crosswords.xml` feed. Unless I'm mistaken (totally possible, sorry!) that means the feed is only discoverable by guessing the URL or digging into your config files.

Anyway! Maybe you're on top of this. Thanks for the puzzles!

**Comment by adamaaronson** [comment]
Thanks for pointing this out, I think I fixed it! Lemme know if it's still messed up.

**Comment by thisisparker** [comment]
I think you fixed it too! Looks great, and thanks again :)
